<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>CCFSharpUtils.Library</RootNamespace>
        <PackageId>CCFSharpUtils</PackageId>
        <Version>0.1.51</Version>
        <PackageReleaseNotes>Incremental updates.</PackageReleaseNotes>
        <Authors>CodeConscious</Authors>
        <Company>CodeConscious</Company>
        <Description>This is a tiny library intended to house my F# utility functions for use across across multiple solutions.</Description>
        <PackageProjectUrl>https://github.com/codeconscious/cc-fsharp-utils/</PackageProjectUrl>
        <RepositoryUrl>https://github.com/codeconscious/cc-fsharp-utils/</RepositoryUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageTags>f# fsharp functional fp utils utility utilities functions codeconscious</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Operators.fs" />
        <Compile Include="Common.fs" />
        <Compile Include="Option.fs" />
        <Compile Include="Num.fs" />
        <Compile Include="Text/String.fs" />
        <Compile Include="Text/Regex.fs" />
        <Compile Include="Collections/Array.fs" />
        <Compile Include="Collections/List.fs" />
        <Compile Include="Collections/Seq.fs" />
        <Compile Include="Collections/Set.fs" />
        <Compile Include="Collections/Map.fs" />
        <Compile Include="Collections/KeyValuePair.fs" />
        <Compile Include="IO\File.fs" />
        <Compile Include="IO\Dir.fs" />
        <Compile Include="FsToolkit/Validation.fs" />
        <None Include="../README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FSharp.Data" Version="6.6.0" />
      <PackageReference Include="FSharpPlus" Version="1.9.1" />
      <PackageReference Include="FsToolkit.ErrorHandling" Version="5.1.0" />
      <PackageReference Update="FSharp.Core" Version="10.0.102" />
    </ItemGroup>

</Project>
