<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="NumTests.fs" />
        <Compile Include="Text/StringTests.fs" />
        <Compile Include="Text/RegexTests.fs" />
        <Compile Include="Collections/SeqTests.fs" />
        <Compile Include="Collections/ListTests.fs" />
        <Compile Include="Collections/ArrayTests.fs" />
        <Compile Include="OptionTests.fs" />
        <Compile Include="IO/FileTests.fs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="8.0.1">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
        <PackageReference Include="xunit" Version="2.9.3"/>
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Update="FSharp.Core" Version="10.1.201" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CCFSharpUtils\CCFSharpUtils.fsproj" />
    </ItemGroup>

</Project>
